# Generated by Django 4.2.30 on 2026-05-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_user_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='report_type',
            field=models.CharField(blank=True, choices=[('', 'Not Assigned'), ('sm_bdm', 'SM & BDM Report'), ('vp_sales_head', 'VP & Sales Head Report'), ('telecallers', 'Telecallers Report'), ('marketing', 'Marketing Report')], default='', max_length=30),
        ),
    ]
