# Generated by Django 4.2.30 on 2026-05-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_update_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='report_type',
            field=models.CharField(max_length=30),
        ),
    ]
