# Generated by Django 4.2.30 on 2026-05-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='layout_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/layouts/'),
        ),
    ]
