# Generated by Django 4.2.30 on 2026-05-27 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_layout_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['id']},
        ),
    ]
