# Generated by Django 4.2.30 on 2026-05-12 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_no', models.CharField(max_length=50)),
                ('area_sqft', models.FloatField(blank=True, null=True)),
                ('facing', models.CharField(blank=True, max_length=100)),
                ('road_width', models.CharField(blank=True, max_length=100)),
                ('rate_per_sqft', models.FloatField(blank=True, null=True)),
                ('total_cost', models.FloatField(blank=True, null=True)),
                ('survey_no', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('sold', 'Sold'), ('available', 'Available')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='projects.project')),
            ],
            options={
                'ordering': ['project', 'plot_no'],
                'unique_together': {('project', 'plot_no')},
            },
        ),
    ]
