# Generated by Django 4.2.30 on 2026-05-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('in_process', 'In Process'), ('blocked', 'Blocked'), ('sold', 'Sold')], default='available', max_length=20),
        ),
    ]
