# Generated by Django 4.2.30 on 2026-05-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='punch_in_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='attendance',
            name='punch_out_address',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
