# Generated by Django 4.2.30 on 2026-05-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_punch_in_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='punch_out_selfie',
            field=models.ImageField(blank=True, null=True, upload_to='attendance/selfies/'),
        ),
    ]
